2024-09-16 20:14:06,417 | WARNING | Неверная скорость для Runner: %s
Traceback (most recent call last):
  File "C:\Programming by pycharm\pythonProjectforURBAN\Module12\M12dz4.py", line 66, in test_walk
    runner = Runner('Nik', -5)
             ^^^^^^^^^^^^^^^^^
  File "C:\Programming by pycharm\pythonProjectforURBAN\Module12\M12dz4.py", line 23, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
2024-09-16 20:14:06,418 | WARNING | Неверный тип данных для объекта Runner: %s
Traceback (most recent call last):
  File "C:\Programming by pycharm\pythonProjectforURBAN\Module12\M12dz4.py", line 74, in test_run
    runner = Runner(777, 5)
             ^^^^^^^^^^^^^^
  File "C:\Programming by pycharm\pythonProjectforURBAN\Module12\M12dz4.py", line 18, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
